---
title: "Analysis of Average Working Hours and GDP around the world from 1970 - 2017"
author:
- familyname: Wu
  othernames: Zhenyu
  address: Monash Universtidy
  email: zwuu0014@student.monash.edu
  correspondingauthor: true
  qualifications:  Master of Business Analytics
- familyname: Katiyar
  othernames: Harsh
  address: Monash University
  email: hkat0008@student.monash.edu
  correspondingauthor: true
  qualifications: Master of Business Analytics
- familyname: Pan
  othernames: Liwen
  address: Monash University
  email: lpan0037@student.monash.edu
  correspondingauthor: true
  qualifications:  Master of Business Analytics
- familyname: Valensia
  othernames: Josephine
  address: Monash Universtidy
  email: jval0011@student.monash.edu
  correspondingauthor: true
  qualifications: Master of Business Analytics
department: Department of Business and Econometrics
organization: Monash University
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries
library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)
library(scales)
```

```{r read-data, echo=FALSE, message = FALSE, warning = FALSE}
Analysis_Data <- read_csv(here::here("Data/Assignment_data.csv"))
```

```{r au_idn, echo=FALSE}
au_idn <- Analysis_Data %>%
  rename(Country = "Entity", 
         avh = "Average annual hours worked by persons engaged (avh) (PWT 9.1 (2019))",
         gdp = "Output-side real GDP per capita (gdppc_o) (PWT 9.1 (2019))") %>%
  select(Country, Year, avh, gdp) %>%
  filter(Country %in% c("Australia", "Indonesia"), 
         Year >=1970 & Year <=2017)
```

```{r avh, echo=FALSE, fig.cap="Comparison of Average annual hours worked by workers in Australia and Indonesia"}
au_idn %>% 
  ggplot(aes(x = Year, 
             y = avh, 
             color = Country)) +
  geom_line() +
    labs(x = "Year",
         y = "hours",
         title = "Average annual hours worked by workers from year 1970-2017",
         caption = "Data from ourworldindata.org (2020)") +
  scale_y_continuous(labels = label_number(big.mark = ",")) +
  theme_bw()
  
```

```{r gdp, echo=FALSE, fig.cap="Comparison of Australia's and Indoensia's GDP per capita"}
au_idn %>% 
  ggplot(aes(x = Year, 
             y = gdp, 
             color = Country)) +
  geom_line()+
    labs(x = "Year",
         y = "USD",
         title = "GDP per capita from year 1970-2017" ,
         caption = "Data from ourworldindata.org (2020)")+
  theme_bw()
  
```
